# Structure list for the CHEM&131 nomenclature site.
# Each entry: (id, section, name_2013, common_or_note, smiles, role)
#   name_2013  : name in current (2013) style; checked name->structure with OPSIN
#   common     : common / older name shown alongside, or a short note
#   role       : "worked" (worked example), "ref" (reference table),
#                "health" (health-connection example), "recog" (recognition only),
#                "generic" (R-group pattern; not name-checked)

S = [
# ---------------- 1. How a name is built: priority ladder (generic patterns) ----------------
("lad_acid",   1, "carboxylic acid", "suffix -oic acid; prefix carboxy-", "*C(=O)O", "generic"),
("lad_anhyd",  1, "anhydride", "-oic anhydride", "*C(=O)OC(=O)*", "generic"),
("lad_ester",  1, "ester", "alkyl -oate", "*C(=O)O*", "generic"),
("lad_amide",  1, "amide", "-amide", "*C(=O)N", "generic"),
("lad_ald",    1, "aldehyde", "-al; prefix oxo- or formyl-", "*C=O", "generic"),
("lad_ket",    1, "ketone", "-one; prefix oxo-", "*C(*)=O", "generic"),
("lad_alc",    1, "alcohol", "-ol; prefix hydroxy-", "*O", "generic"),
("lad_thiol",  1, "thiol", "-thiol; prefix sulfanyl-", "*S", "generic"),
("lad_amine",  1, "amine", "-amine; prefix amino-", "*N", "generic"),
("lad_ene",    1, "alkene", "-ene", "*C=C*", "generic"),
("lad_yne",    1, "alkyne", "-yne", "*C#C*", "generic"),
("lad_alkoxy", 1, "alkoxy (ether)", "prefix alkoxy-", "*O*", "generic"),
("lad_halo",   1, "halogen", "fluoro- chloro- bromo- iodo-", "*[X]", "generic"),
("lad_nitro",  1, "nitro", "prefix nitro-", "*[N+](=O)[O-]", "generic"),

# ---------------- 2. Alkanes, cycloalkanes, alkyl groups, substituted alkanes ----------------
("anat", 1, "3-methylpent-4-en-2-ol", "OH is the suffix, so it gets the lowest number", "CC(O)C(C)C=C", "worked"),
("cyc3", 2, "cyclopropane", "", "C1CC1", "ref"),
("cyc4", 2, "cyclobutane", "", "C1CCC1", "ref"),
("cyc5", 2, "cyclopentane", "", "C1CCCC1", "ref"),
("cyc6", 2, "cyclohexane", "", "C1CCCCC1", "ref"),
("cyc7", 2, "cycloheptane", "", "C1CCCCCC1", "ref"),
("cyc8", 2, "cyclooctane", "", "C1CCCCCCC1", "ref"),
("alk_me",   2, "methyl", "", "*C", "generic"),
("alk_et",   2, "ethyl", "", "*CC", "generic"),
("alk_pr",   2, "propyl", "n-propyl", "*CCC", "generic"),
("alk_bu",   2, "butyl", "n-butyl", "*CCCC", "generic"),
("alk_ipr",  2, "propan-2-yl", "isopropyl", "*C(C)C", "generic"),
("alk_ibu",  2, "2-methylpropyl", "isobutyl", "*CC(C)C", "generic"),
("alk_sbu",  2, "butan-2-yl", "sec-butyl", "*C(C)CC", "generic"),
("alk_tbu",  2, "tert-butyl", "2-methylpropan-2-yl", "*C(C)(C)C", "generic"),
("ex_octane", 2, "3-bromo-2-chloro-5-ethyl-4,4-dimethyloctane", "", "CC(Cl)C(Br)C(C)(C)C(CC)CCC", "worked"),
("ex_heptane", 2, "3-fluoro-2-methyl-4-(propan-2-yl)heptane", "older: 3-fluoro-4-isopropyl-2-methylheptane", "CC(C)C(F)C(C(C)C)CCC", "worked"),
("ex_cyhex", 2, "1-(butan-2-yl)-3-nitrocyclohexane", "older: 1-sec-butyl-3-nitrocyclohexane; b before n sets numbering", "CCC(C)C1CCCC(C1)[N+](=O)[O-]", "worked"),
("ex_tworing", 2, "3-phenylcyclohexan-1-one", "two separate rings: ketone ring is parent", "O=C1CCCC(C1)c1ccccc1", "worked"),

# ---------------- 3. Alkenes, alkynes, cis/trans, E/Z ----------------
("ene1", 3, "4,4-difluoro-3-methylbut-1-ene", "", "C=CC(C)C(F)F", "worked"),
("ene2", 3, "1,1-difluoro-2-methylbuta-1,3-diene", "added 'a': buta-1,3-diene", "FC(F)=C(C)C=C", "worked"),
("ene3", 3, "5-methylcyclopenta-1,3-diene", "", "CC1C=CC=C1", "worked"),
("yne1", 3, "4,4-difluoro-3-methylbut-1-yne", "", "C#CC(C)C(F)F", "worked"),
("yne2", 3, "pent-3-en-1-yne", "yne nearer chain end sets numbering", "C#CC=CC", "worked"),
("yne3", 3, "pent-1-en-4-yne", "tie: alkene gets the lower number", "C=CCC#C", "worked"),
("ct1", 3, "(2Z)-but-2-ene", "cis-but-2-ene", "C/C=C\\C", "worked"),
("ct2", 3, "(2E)-but-2-ene", "trans-but-2-ene", "C/C=C/C", "worked"),
("ct3", 3, "cis-1,2-dimethylcyclopentane", "cis on a ring", "C[C@@H]1CCC[C@@H]1C", "worked"),
("ct4", 3, "trans-1,2-dimethylcyclopentane", "trans on a ring", "C[C@@H]1CCC[C@H]1C", "worked"),
("ez1", 3, "(E)-1-bromo-2-chloro-2-fluoro-1-iodoethene", "no cis/trans possible: needs E/Z", "F/C(Cl)=C(/Br)I", "worked"),
("ez2", 3, "(2E)-2-bromobut-2-ene", "methyls on same side, yet E", "C/C(Br)=C\\C", "worked"),

# ---------------- 4. Alcohols, ethers, alkyl halides, thiols ----------------
("alc1", 4, "ethanol", "ethyl alcohol", "CCO", "worked"),
("alc2", 4, "but-3-en-2-ol", "", "CC(O)C=C", "worked"),
("alc3", 4, "2-aminocyclobutan-1-ol", "", "NC1CCC1O", "worked"),
("alc_p", 4, "propan-1-ol", "1° alcohol", "CCCO", "worked"),
("alc_s", 4, "propan-2-ol", "isopropyl alcohol; 2° alcohol", "CC(C)O", "health"),
("alc_t", 4, "2-methylpropan-2-ol", "tert-butyl alcohol; 3° alcohol", "CC(C)(C)O", "worked"),
("diol", 4, "ethane-1,2-diol", "ethylene glycol", "OCCO", "health"),
("triol", 4, "propane-1,2,3-triol", "glycerol", "OCC(O)CO", "health"),
("xylitol", 4, "pentane-1,2,3,4,5-pentol", "xylitol (sugar substitute that fights tooth decay); a meso compound", "OC[C@H](O)[C@@H](O)[C@H](O)CO", "health"),
("ether1", 4, "ethoxyethane", "diethyl ether", "CCOCC", "health"),
("ether2", 4, "1-methoxypropane", "methyl propyl ether", "CCCOC", "worked"),
("halo1", 4, "chloroethane", "ethyl chloride (cold spray for minor pain)", "CCCl", "health"),
("halo2", 4, "2-bromo-2-methylpropane", "tert-butyl bromide", "CC(C)(C)Br", "worked"),
("halo3", 4, "2-bromo-2-chloro-1,1,1-trifluoroethane", "halothane (inhaled anesthetic)", "FC(F)(F)C(Cl)Br", "health"),
("nitro_ex", 4, "2-methyl-1-nitropropane", "nitro is always a prefix, like a halogen", "CC(C)C[N+](=O)[O-]", "worked"),
("nitro_tnt", 4, "2-methyl-1,3,5-trinitrobenzene", "TNT; a soil and groundwater contaminant cleaned up by bioremediation", "Cc1c(cc(cc1[N+](=O)[O-])[N+](=O)[O-])[N+](=O)[O-]", "recog"),
("nitro_furan", 4, "1-{[(E)-(5-nitrofuran-2-yl)methylidene]amino}imidazolidine-2,4-dione", "nitrofurantoin (Macrobid), a common UTI antibiotic", "O=C1CN(/N=C/c2ccc([N+](=O)[O-])o2)C(=O)N1", "recog"),
("nitro_metro", 4, "2-(2-methyl-5-nitro-1H-imidazol-1-yl)ethan-1-ol", "metronidazole (Flagyl), used for dental and other infections", "Cc1ncc([N+](=O)[O-])n1CCO", "recog"),
("nitro_ntg", 4, "propane-1,2,3-triyl trinitrate", "nitroglycerin: NOT a nitro compound (NO2 on oxygen, a nitrate ester)", "[O-][N+](=O)OCC(CO[N+](=O)[O-])O[N+](=O)[O-]", "recog"),
("thiol1", 4, "ethanethiol", "", "CCS", "worked"),
("thiol2", 4, "2-aminoethane-1-thiol", "cysteamine", "NCCS", "health"),
("disulf", 4, "(methyldisulfanyl)methane", "dimethyl disulfide", "CSSC", "worked"),

# ---------------- 5. Aldehydes and ketones ----------------
("ald1", 5, "methanal", "formaldehyde", "C=O", "worked"),
("ald2", 5, "ethanal", "acetaldehyde", "CC=O", "worked"),
("ald3", 5, "4-hydroxybut-2-enal", "", "OCC=CC=O", "worked"),
("ald4", 5, "4-oxopentanal", "aldehyde outranks ketone", "CC(=O)CCC=O", "worked"),
("ald5", 5, "cyclohexanecarbaldehyde", "CHO carbon not in the ring", "O=CC1CCCCC1", "worked"),
("ket1", 5, "propan-2-one", "acetone", "CC(C)=O", "health"),
("ket2", 5, "butan-2-one", "methyl ethyl ketone", "CCC(C)=O", "worked"),
("ket3", 5, "cyclohex-3-en-1-one", "", "O=C1CCC=CC1", "worked"),
("ket4", 5, "3-hydroxybutan-2-one", "", "CC(O)C(C)=O", "worked"),
("ket5", 5, "4-(dimethylamino)pent-4-en-2-one", "corrected from handout's 4-amino-N,N-dimethylpent-4-en-2-one", "CC(=O)CC(=C)N(C)C", "worked"),

# ---------------- 6. Chirality and R/S ----------------
("rs1", 6, "(R)-bromochlorofluoroiodomethane", "Rule 1 only: I > Br > Cl > F", "F[C@@](Cl)(Br)I", "worked"),
("rs2", 6, "(2R)-butan-2-ol", "", "C[C@@H](O)CC", "worked"),
("rs3", 6, "(2S)-butan-2-ol", "mirror image of (2R)", "C[C@H](O)CC", "worked"),
("rs4", 6, "(2S)-2-aminopropanoic acid", "L-alanine", "C[C@H](N)C(=O)O", "worked"),
("rs5", 6, "(2R)-2,3-dihydroxypropanal", "D-glyceraldehyde; Rule 3 (C=O counts as two O)", "OC[C@@H](O)C=O", "worked"),
("meso1", 6, "(2R,3R)-butane-2,3-diol", "chiral: has a non-superimposable mirror image", "C[C@@H](O)[C@@H](C)O", "worked"),
("meso2", 6, "(2R,3S)-butane-2,3-diol", "meso: two chiral centers, internal mirror plane, not chiral", "C[C@H](O)[C@@H](C)O", "worked"),
("meso3", 6, "(2R,3S)-2,3-dihydroxybutanedioic acid", "meso-tartaric acid", "OC(=O)[C@@H](O)[C@@H](O)C(=O)O", "worked"),
("rs6", 6, "(2S)-2-[4-(2-methylpropyl)phenyl]propanoic acid", "(S)-ibuprofen, the active enantiomer", "C[C@H](C(=O)O)c1ccc(CC(C)C)cc1", "health"),

# ---------------- 7. Carboxylic acids, esters, salts, anhydrides ----------------
("acid1", 7, "formic acid", "methanoic acid", "OC=O", "worked"),
("acid2", 7, "acetic acid", "ethanoic acid", "CC(=O)O", "worked"),
("acid3", 7, "butanoic acid", "butyric acid", "CCCC(=O)O", "worked"),
("acid4", 7, "2-amino-3-phenylpropanoic acid", "phenylalanine", "NC(Cc1ccccc1)C(=O)O", "health"),
("acid5", 7, "2,2-dimethyl-3,4-dioxobutanoic acid", "", "O=CC(=O)C(C)(C)C(=O)O", "worked"),
("acid6", 7, "2-formyl-4-oxocyclohexane-1-carboxylic acid", "ring: -carboxylic acid; formyl for CHO", "OC(=O)C1CCC(=O)CC1C=O", "worked"),
("salt1", 7, "sodium acetate", "", "CC(=O)[O-].[Na+]", "worked"),
("salt2", 7, "lithium 2-aminopropanoate", "", "CC(N)C(=O)[O-].[Li+]", "worked"),
("salt3", 7, "sodium chloroacetate", "", "ClCC(=O)[O-].[Na+]", "worked"),
("salt4", 7, "ammonium 2-methoxycyclobutane-1-carboxylate", "", "COC1CCC1C(=O)[O-].[NH4+]", "worked"),
("est1", 7, "ethyl acetate", "", "CCOC(C)=O", "worked"),
("est2", 7, "propan-2-yl 2,2-dimethylpropanoate", "isopropyl 2,2-dimethylpropanoate", "CC(C)OC(=O)C(C)(C)C", "worked"),
("est3", 7, "cyclohexyl phenylacetate", "", "O=C(Cc1ccccc1)OC1CCCCC1", "worked"),
("est5", 7, "methyl 3-hydroxycyclopentane-1-carboxylate", "", "COC(=O)C1CCC(O)C1", "worked"),
("est6", 7, "2-(acetyloxy)benzoic acid", "aspirin (an ester and an acid)", "CC(=O)Oc1ccccc1C(=O)O", "health"),
("est7", 7, "ethyl 4-aminobenzoate", "benzocaine (topical dental anesthetic)", "CCOC(=O)c1ccc(N)cc1", "health"),
("anh1", 7, "acetic anhydride", "used to make aspirin", "CC(=O)OC(C)=O", "worked"),
("anh2", 7, "benzoic anhydride", "", "O=C(OC(=O)c1ccccc1)c1ccccc1", "worked"),

# ---------------- 8. Amines, amine salts, amides ----------------
("am1", 8, "propan-1-amine", "propylamine", "CCCN", "worked"),
("am2", 8, "N,N-diethylbut-3-en-2-amine", "N marks groups on nitrogen", "CCN(CC)C(C)C=C", "worked"),
("am3", 8, "3-methoxycyclohexan-1-amine", "", "COC1CCCC(N)C1", "worked"),
("am_p", 8, "ethanamine", "ethylamine; 1° amine", "CCN", "worked"),
("am_s", 8, "N-methylethanamine", "ethylmethylamine; 2° amine", "CCNC", "worked"),
("am_t", 8, "N,N-dimethylethanamine", "ethyldimethylamine; 3° amine", "CCN(C)C", "worked"),
("amsalt", 8, "ethanaminium chloride", "ethylamine hydrochloride", "CC[NH3+].[Cl-]", "worked"),
("amd1", 8, "butanamide", "", "CCCC(N)=O", "worked"),
("amd2", 8, "benzamide", "", "NC(=O)c1ccccc1", "worked"),
("amd3", 8, "N-(4-hydroxyphenyl)acetamide", "acetaminophen", "CC(=O)Nc1ccc(O)cc1", "health"),
("amd4", 8, "2-(diethylamino)-N-(2,6-dimethylphenyl)acetamide", "lidocaine (local anesthetic)", "CCN(CC)CC(=O)Nc1c(C)cccc1C", "health"),
("pep", 8, "glycyl-L-alanine", "a dipeptide; the amide is the peptide bond", "NCC(=O)N[C@@H](C)C(=O)O", "health"),

# ---------------- 9. Biomolecule connections (recognition) ----------------
("bio_pal",  9, "hexadecanoic acid", "palmitic acid (C16)", "CCCCCCCCCCCCCCCC(=O)O", "recog"),
("bio_ste",  9, "octadecanoic acid", "stearic acid (C18)", "CCCCCCCCCCCCCCCCCC(=O)O", "recog"),
("bio_ole",  9, "(9Z)-octadec-9-enoic acid", "oleic acid (cis)", "CCCCCCCC/C=C\\CCCCCCCC(=O)O", "recog"),
("bio_ela",  9, "(9E)-octadec-9-enoic acid", "elaidic acid (trans fat)", "CCCCCCCC/C=C/CCCCCCCC(=O)O", "recog"),
("bio_cys",  9, "L-cysteine", "thiol in proteins", "N[C@@H](CS)C(=O)O", "recog"),
("bio_cyss", 9, "L-cystine", "two cysteines joined by a disulfide", "N[C@@H](CSSC[C@H](N)C(=O)O)C(=O)O", "recog"),
("bio_chol", 9, "cholesterol", "four fused rings (steroid core)", "CC(C)CCC[C@@H](C)[C@H]1CC[C@@H]2[C@@]1(CC[C@H]3[C@H]2CC=C4[C@@]3(CC[C@@H](C4)O)C)C", "recog"),
("bio_pyr",  9, "pyridine", "", "c1ccncc1", "recog"),
("bio_pyrr", 9, "1H-pyrrole", "pyrrole", "c1cc[nH]c1", "recog"),
("bio_imid", 9, "1H-imidazole", "imidazole (in histidine)", "c1c[nH]cn1", "recog"),
("bio_pyrm", 9, "pyrimidine", "parent of C, T, U", "c1cncnc1", "recog"),
("bio_pur",  9, "7H-purine", "purine; parent of A, G", "c1ncc2[nH]cnc2n1", "recog"),
("bio_ade",  9, "9H-purin-6-amine", "adenine", "Nc1ncnc2[nH]cnc12", "recog"),
("bio_pest", 9, "methyl dihydrogen phosphate", "phosphoester (C–O–P)", "COP(=O)(O)O", "recog"),
("bio_panh", 9, "diphosphoric acid", "phosphoanhydride (P–O–P)", "OP(=O)(O)OP(=O)(O)O", "recog"),
("bio_phe",  9, "dimethyl hydrogen phosphate", "phosphodiester (C–O–P–O–C), the DNA/RNA backbone pattern", "COP(=O)(O)OC", "recog"),
("bio_atp",  9, "adenosine 5'-triphosphate", "ATP: one phosphoester, two phosphoanhydrides", "Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)(O)OP(=O)(O)OP(=O)(O)O)[C@@H](O)[C@H]1O", "recog"),
]

# Chain/ring numbering shown on worked examples: atom indices for locants 1, 2, 3, ...
LOCANTS = {
 "ex_octane": [0,1,3,5,8,11,12,13], "ex_heptane": [0,1,3,5,9,10,11], "ex_cyhex": [4,9,8,7,6,5],
 "ex_tworing": [1,6,5,4,3,2], "ene1": [0,1,2,4], "ene2": [1,3,5,6], "ene3": [2,3,4,5,1],
 "yne1": [0,1,2,4], "yne2": [0,1,2,3,4], "yne3": [0,1,2,3,4], "alc2": [0,1,3,4], "alc3": [4,1,2,3],
 "nitro_ex": [3,1,0], "anat": [0,1,3,5,6],
 "ald3": [4,3,2,1], "ald4": [5,4,3,1,0], "ket3": [1,6,5,4,3,2], "ket4": [4,3,1,0], "ket5": [0,1,3,4,5],
 "acid5": [7,4,2,1], "acid6": [3,9,8,6,5,4], "salt4": [5,2,3,4], "est5": [4,9,7,6,5],
 "am2": [6,5,7,8], "am3": [6,8,2,3,4,5],
}
# Figures that show (R)/(S) labels drawn on the structure
SHOW_CIP = {"rs1","rs2","rs3","rs4","rs5","rs6","meso1","meso2","meso3"}

S.append(("alk_ph", 2, "phenyl", "a benzene ring used as a substituent", "*c1ccccc1", "generic"))

# Practice problems. Structures are generated from the name by OPSIN at build time,
# so the drawing can never disagree with the answer.
#   (id, section, answer_name, kind, alt_for_screen_readers, why)
#   kind "name": student sees the structure and names it
#   kind "draw": student sees the name and draws it; answer shows the structure
PRACTICE = [
 ("p2a", 2, "2,3-dimethylpentane", "name", "A five-carbon chain with one-carbon branches on the second and third carbons.",
  "The longest chain has five carbons (pentane). Numbering from the end nearer the branches puts the methyl groups at 2 and 3, not 3 and 4."),
 ("p2b", 2, "4-ethyl-2,2-dimethylhexane", "name", "A six-carbon chain with two one-carbon branches on carbon two and a two-carbon branch on carbon four.",
  "Six-carbon chain (hexane). The locant set {2,2,4} beats {3,5,5} at the first point of difference. Ethyl comes before methyl alphabetically; the 'di' in dimethyl is ignored when alphabetizing."),
 ("p2c", 2, "1-ethyl-3-methylcyclohexane", "draw", "",
  "A ring with two groups: both numberings give 1,3, so the tie goes to the group first in alphabetical order, ethyl."),
 ("p3a", 3, "(2Z)-pent-2-ene", "name", "A five-carbon chain with a double bond between carbons two and three; the two chain carbons attached to the double bond are on the same side.",
  "The two higher-priority groups (CH3 on C2, CH2CH3 on C3) are on the same side, so it is Z. Here cis and Z agree."),
 ("p3b", 3, "3-methylbut-1-yne", "name", "A four-carbon chain with a triple bond at one end and a one-carbon branch on carbon three.",
  "Number from the end nearer the triple bond: the triple bond starts at C1 and the methyl is on C3."),
 ("p3c", 3, "(2E)-3-methylpent-2-ene", "draw", "",
  "On C3, ethyl outranks methyl. On C2, CH3 outranks H. E means those two higher-priority groups are on opposite sides."),
 ("p4a", 4, "pentan-3-ol", "name", "A five-carbon chain with an OH group on the middle carbon.",
  "The OH is on C3 from either end. The carbon holding the OH is bonded to two other carbons, so this is a secondary (2°) alcohol."),
 ("p4b", 4, "2-methylbutan-2-ol", "name", "A four-carbon chain with both a one-carbon branch and an OH group on carbon two.",
  "Number from the end that gives the OH the lowest locant: C2. The OH carbon is bonded to three carbons: a tertiary (3°) alcohol."),
 ("p4c", 4, "1-methoxypropane", "draw", "",
  "The ether oxygen joins a one-carbon group (methoxy) to a three-carbon chain (propane) at its first carbon. Common name: methyl propyl ether."),
 ("p4d", 4, "propane-1-thiol", "name", "A three-carbon chain with an SH group on an end carbon.",
  "The -thiol suffix keeps the final 'e' of propane because 'thiol' starts with a consonant."),
 ("p5a", 5, "3-methylbutanal", "name", "A four-carbon chain ending in an aldehyde group (CHO), with a one-carbon branch on carbon three.",
  "The aldehyde carbon is always C1, so no locant is needed for '-al'. The methyl lands on C3."),
 ("p5b", 5, "pentan-3-one", "name", "A five-carbon chain with a C=O on the middle carbon.",
  "The carbonyl is on C3 from either end. Unlike an aldehyde, a ketone carbonyl can be anywhere except the end, so it needs a locant."),
 ("p5c", 5, "2-methylcyclopentan-1-one", "draw", "",
  "The carbonyl carbon is C1 of the ring; number toward the methyl so it gets 2."),
 ("p6a", 6, "(2S)-2-chlorobutane", "name", "A four-carbon chain with a chlorine on carbon two, drawn with a wedge and dash to show its three-dimensional arrangement.",
  "Priorities: Cl > CH2CH3 > CH3 > H. With H pointing away, the path Cl → ethyl → methyl runs counterclockwise: S."),
 ("p6b", 6, "(2R)-2-hydroxypropanoic acid", "name", "A three-carbon acid with an OH on carbon two, drawn with a wedge and dash; this is lactic acid.",
  "Priorities: OH > COOH > CH3 > H. (R)-lactic acid; the (S) form is the one your muscles make during intense exercise."),
 ("p6c", 6, "(2R,3S)-2,3-dibromobutane", "name", "A four-carbon chain with bromines on carbons two and three, drawn with wedges and dashes.",
  "Two chiral centers, R and S, and the molecule has an internal mirror plane. It is meso: not chiral, and no optical activity."),
 ("p7a", 7, "propyl acetate", "name", "An ester: a two-carbon acid part (with the C=O) bonded through oxygen to a three-carbon group.",
  "Name the group on the single-bonded oxygen first (propyl), then the acid part with -ate (acetate; ethanoate is also correct). Propyl acetate smells like pears."),
 ("p7b", 7, "potassium butanoate", "draw", "",
  "Remove the acid H from butanoic acid; the -oic acid ending becomes -oate, and the metal is named first."),
 ("p7c", 7, "2-methylpropanoic acid", "name", "A three-carbon carboxylic acid with a one-carbon branch on carbon two.",
  "The COOH carbon is C1; the branch is on C2."),
 ("p8a", 8, "butan-2-amine", "name", "A four-carbon chain with an NH2 group on carbon two.",
  "Number to give the amine the lowest locant: 2. One carbon is bonded to the nitrogen, so this is a primary (1°) amine, even though the carbon is a 2° carbon."),
 ("p8b", 8, "N,N-dimethylmethanamine", "name", "A nitrogen bonded to three one-carbon groups.",
  "Three carbons on nitrogen: a tertiary (3°) amine. Common name: trimethylamine, the smell of fish."),
 ("p8c", 8, "N-methylbutanamide", "draw", "",
  "A four-carbon amide (butanamide) with one methyl group on the nitrogen, shown by N-."),
]

# ---------------- 10. Aromatic compounds (section file 03b) ----------------
S += [
("ar_benz", 10, "benzene", "", "c1ccccc1", "ref"),
("ar_naph", 10, "naphthalene", "two fused benzene rings; mothballs", "c1ccc2ccccc2c1", "recog"),
("ar_cl", 10, "chlorobenzene", "", "Clc1ccccc1", "worked"),
("ar_no2", 10, "nitrobenzene", "", "[O-][N+](=O)c1ccccc1", "worked"),
("ar_et", 10, "ethylbenzene", "", "CCc1ccccc1", "worked"),
("ar_tol", 10, "toluene", "methylbenzene", "Cc1ccccc1", "ref"),
("ar_phol", 10, "phenol", "hydroxybenzene", "Oc1ccccc1", "ref"),
("ar_anil", 10, "aniline", "benzenamine", "Nc1ccccc1", "ref"),
("ar_anis", 10, "anisole", "methoxybenzene", "COc1ccccc1", "ref"),
("ar_bzac", 10, "benzoic acid", "", "OC(=O)c1ccccc1", "ref"),
("ar_bzal", 10, "benzaldehyde", "", "O=Cc1ccccc1", "ref"),
("ar_acph", 10, "1-phenylethan-1-one", "acetophenone", "CC(=O)c1ccccc1", "ref"),
("ar_bzph", 10, "diphenylmethanone", "benzophenone", "O=C(c1ccccc1)c1ccccc1", "ref"),
("ar_bn", 10, "benzyl", "a benzene ring plus one CH2", "*Cc1ccccc1", "generic"),
("ar_o", 10, "1,2-dichlorobenzene", "ortho (o-): next door", "Clc1ccccc1Cl", "worked"),
("ar_m", 10, "1,3-dichlorobenzene", "meta (m-): one carbon between", "Clc1cccc(Cl)c1", "worked"),
("ar_p", 10, "1,4-dichlorobenzene", "para (p-): across the ring", "Clc1ccc(Cl)cc1", "worked"),
("ar_ex1", 10, "3-methylphenol", "m-cresol", "Cc1cccc(O)c1", "worked"),
("ar_ex2", 10, "2-methoxybenzaldehyde", "o-anisaldehyde", "COc1ccccc1C=O", "worked"),
("ar_ex3", 10, "3-aminobenzoic acid", "m-aminobenzoic acid", "Nc1cccc(c1)C(=O)O", "worked"),
("ar_ex4", 10, "3,4-dichloro-N-methylaniline", "", "CNc1ccc(Cl)c(Cl)c1", "worked"),
("ar_tnt", 10, "2-methyl-1,3,5-trinitrobenzene", "TNT (2,4,6-trinitrotoluene)", "Cc1c([N+](=O)[O-])cc([N+](=O)[O-])cc1[N+](=O)[O-]", "worked"),
("ar_eug", 10, "2-methoxy-4-(prop-2-en-1-yl)phenol", "eugenol (clove oil), used in dental cements", "COc1cc(CC=C)ccc1O", "health"),
("ar_bht", 10, "2,6-di-tert-butyl-4-methylphenol", "BHT, an antioxidant food preservative", "Cc1cc(C(C)(C)C)c(O)c(C(C)(C)C)c1", "health"),
("ar_oxy", 10, "(2-hydroxy-4-methoxyphenyl)(phenyl)methanone", "oxybenzone, a sunscreen UV filter", "COc1ccc(C(=O)c2ccccc2)c(O)c1", "health"),
]
LOCANTS.update({
 "ar_o": [1, 6, 5, 4, 3, 2], "ar_m": [1, 7, 5, 4, 3, 2], "ar_p": [1, 2, 3, 4, 6, 7],
 "ar_ex1": [5, 7, 1, 2, 3, 4], "ar_ex2": [7, 2, 3, 4, 5, 6], "ar_ex3": [5, 6, 1, 2, 3, 4],
 "ar_ex4": [2, 9, 7, 5, 4, 3], "ar_tnt": [2, 1, 12, 11, 7, 6], "ar_eug": [10, 2, 3, 4, 8, 9],
})
PRACTICE += [
 ("p_ar1", 10, "1-bromo-3-chlorobenzene", "name", "A benzene ring with a bromine and a chlorine separated by one ring carbon.",
  "Neither group is a retained parent, so the parent is benzene. Bromo comes first alphabetically, so it gets C1, and the chlorine lands on C3. Common style: m-bromochlorobenzene."),
 ("p_ar2", 10, "4-nitrophenol", "name", "A benzene ring with an OH group and, directly across the ring, an NO2 group.",
  "The OH makes this a phenol, and the OH carbon is C1. The nitro group is across the ring at C4. Common style: p-nitrophenol."),
 ("p_ar3", 10, "2-ethylaniline", "draw", "",
  "Aniline is benzene with an NH2; the NH2 carbon is C1. The ethyl group goes on the next carbon, C2 (ortho)."),
]
